# Generated by Django 2.1.8 on 2024-04-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clustergene',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('studyid', models.CharField(max_length=254)),
                ('cluster', models.CharField(max_length=254, null=True)),
                ('model', models.CharField(max_length=254, null=True)),
                ('gene', models.TextField(max_length=254, null=True)),
                ('cv', models.FloatField(max_length=254, null=True)),
                ('mean', models.FloatField(max_length=254, null=True)),
                ('organism', models.TextField(null=True)),
                ('experiment_type', models.TextField(null=True)),
                ('tissue_cell_type', models.TextField(null=True)),
                ('strategy', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaIndicator',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('studyid', models.CharField(max_length=254)),
                ('model', models.CharField(max_length=254)),
                ('rmse', models.FloatField(null=True)),
                ('rsq', models.FloatField(null=True)),
                ('aic', models.FloatField(null=True)),
                ('cluster', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='geneinfo',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('geneid', models.IntegerField(db_index=True, null=True)),
                ('gene', models.TextField(max_length=254, null=True)),
                ('synonyms', models.TextField(max_length=254, null=True)),
                ('description', models.TextField(max_length=254, null=True)),
                ('ensembl', models.TextField(max_length=254, null=True)),
                ('specie', models.TextField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GO',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('GO_ID', models.TextField(max_length=254)),
                ('Description', models.CharField(max_length=254, null=True)),
                ('ONT', models.TextField(max_length=254, null=True)),
                ('GeneRatio', models.TextField(max_length=254, null=True)),
                ('BgRatio', models.TextField(max_length=254, null=True)),
                ('pvalue', models.FloatField(max_length=254, null=True)),
                ('p_adjust', models.FloatField(null=True)),
                ('qvalue', models.FloatField(null=True)),
                ('geneID', models.TextField(max_length=254)),
                ('Count', models.IntegerField(db_index=True, null=True)),
                ('cluster', models.CharField(max_length=254, null=True)),
                ('studyid', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='KEGG',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('KEGG_ID', models.TextField(max_length=254)),
                ('Description', models.CharField(max_length=254, null=True)),
                ('GeneRatio', models.TextField(max_length=254, null=True)),
                ('BgRatio', models.TextField(max_length=254, null=True)),
                ('pvalue', models.FloatField(null=True)),
                ('p_adjust', models.FloatField(null=True)),
                ('qvalue', models.FloatField(null=True)),
                ('geneID', models.TextField(max_length=254)),
                ('Count', models.IntegerField(db_index=True, null=True)),
                ('cluster', models.CharField(max_length=254, null=True)),
                ('studyid', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ModelDF',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('cluster', models.CharField(max_length=254, null=True)),
                ('model', models.CharField(max_length=254, null=True)),
                ('parameters', models.TextField(max_length=254, null=True)),
                ('exp', models.TextField(max_length=254, null=True)),
                ('studyid', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sampleinfo',
            fields=[
                ('studyid', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('accession', models.CharField(max_length=254, null=True)),
                ('sample', models.TextField(max_length=254, null=True)),
                ('time', models.TextField(max_length=254, null=True)),
                ('phototime', models.TextField(max_length=254, null=True)),
                ('unit', models.CharField(max_length=254, null=True)),
                ('related_factor', models.TextField(null=True)),
                ('drug', models.TextField(null=True)),
                ('drug_concentration', models.TextField(null=True)),
                ('perturbation', models.TextField(null=True)),
                ('tissue_cell_type', models.TextField(null=True)),
                ('organism', models.TextField(null=True)),
                ('data_source', models.TextField(null=True)),
                ('strategy', models.CharField(max_length=254, null=True)),
                ('pmid', models.TextField(null=True)),
                ('disease', models.TextField(null=True)),
                ('other', models.TextField(null=True)),
                ('experiment_type', models.TextField(null=True)),
                ('Data_prepro_info', models.TextField(null=True)),
            ],
        ),
    ]
